DROP TABLE IF EXISTS DealerLedgerMetadata CASCADE;
DROP TABLE IF EXISTS DealerLedgerMetadataCategory CASCADE;
DROP TABLE IF EXISTS DealerVehicleSalesLedger CASCADE;
DROP TABLE IF EXISTS DealerPostSalesLedger CASCADE;

CREATE TABLE DealerLedgerMetadataCategory
(
   id integer,
   name varchar(100),
   timestamp timestamp without time zone, 
   CONSTRAINT DLMC_PK PRIMARY KEY (id)
) 
WITH (
  OIDS = FALSE
)
;

CREATE TABLE DealerLedgerMetadata
(
   id integer NOT NULL,
   name varchar(100) NOT NULL,
   displayName varchar(100) NOT NULL,
   type varchar(25) NOT NULL,
   options varchar,
   dealerID integer NOT NULL,
   categoryID integer NOT NULL,
   CONSTRAINT DLM_PK PRIMARY KEY (id), 
   CONSTRAINT DLM_FK1 FOREIGN KEY (dealerID) REFERENCES Dealer (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
   CONSTRAINT DLM_FK2 FOREIGN KEY (categoryID) REFERENCES DealerLedgerMetadataCategory (id) ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;

CREATE TABLE DealerVehicleSalesLedger
(
   timestamp timestamp without time zone NOT NULL,
   timeEnd timestamp without time zone NOT NULL,
   validDate date NOT NULL,
   contractNo integer NOT NULL,
   dealerID integer NOT NULL,
   model varchar(100),
   type varchar(100),
   color varchar(100),
   lpNumber varchar(100),
   frameNo varchar(100),
   manufacturerDebitDate date,
   warehousingDate date,
   salesDate date,
   guidingPrice double precision NOT NULL DEFAULT 0,
   customerName varchar(100),
   identificationNo varchar(100),
   salesConsultant varchar(100),
   customerType varchar(100),
   vehicleInvoiceAmount double precision NOT NULL DEFAULT 0,
   accessoryInvoiceAmount double precision NOT NULL DEFAULT 0,
   vehicleMarkup double precision NOT NULL DEFAULT 0,
   invoiceType varchar(100),
   invoiceDate date,
   posBank varchar(100),
   posCharge double precision NOT NULL DEFAULT 0,
   cash double precision NOT NULL DEFAULT 0,
   cheque double precision NOT NULL DEFAULT 0,
   transfer double precision NOT NULL DEFAULT 0,
   paidSubscription double precision NOT NULL DEFAULT 0,
   paidRemainder double precision NOT NULL DEFAULT 0,
   refund double precision NOT NULL DEFAULT 0,
   vehicleSalesRevenue double precision NOT NULL DEFAULT 0,
   vehicleSalesCost double precision NOT NULL DEFAULT 0,
   usedVehicleCharge double precision NOT NULL DEFAULT 0,
   usedVehicleCost double precision NOT NULL DEFAULT 0,
   usedVehicleSellingPrice double precision NOT NULL DEFAULT 0,
   distributor varchar(100),
   usedVehicleManufacturerSubsidy double precision NOT NULL DEFAULT 0,
   accessorySalesRevenue double precision NOT NULL DEFAULT 0,
   accessorySalesCostBuyerPart double precision NOT NULL DEFAULT 0,
   accessorySalesCostGiftPart double precision NOT NULL DEFAULT 0,
   insuranceRebateMargin double precision NOT NULL DEFAULT 0,
   insuranceCost double precision NOT NULL DEFAULT 0,
   insuranceAgency varchar(100),
   lpRevenue double precision NOT NULL DEFAULT 0,
   lpCost double precision NOT NULL DEFAULT 0,
   installmentCharge double precision NOT NULL DEFAULT 0,
   fcCommission double precision NOT NULL DEFAULT 0,
   installmentManufacturerSubsidy double precision NOT NULL DEFAULT 0,
   installmentOthers double precision NOT NULL DEFAULT 0,
   installmentAgency varchar(100),
   extendedWarrantyRevenue double precision NOT NULL DEFAULT 0,
   extendedWarrantyCost double precision NOT NULL DEFAULT 0,
   financialLeasingMargin double precision NOT NULL DEFAULT 0,
   exitWarehouseMargin double precision NOT NULL DEFAULT 0,
   inspectionMargin double precision NOT NULL DEFAULT 0,
   memberCardRevenue double precision NOT NULL DEFAULT 0,
   memberCardCost double precision NOT NULL DEFAULT 0,
   otherMargin double precision NOT NULL DEFAULT 0,
   postSalesVoucherManHourPart double precision NOT NULL DEFAULT 0,
   postSalesVoucherDecorationPart double precision NOT NULL DEFAULT 0,
   postSalesVoucherAccessoryPart double precision NOT NULL DEFAULT 0,
   fuelCard double precision NOT NULL DEFAULT 0,
   gasoline double precision NOT NULL DEFAULT 0,
   otherGift double precision NOT NULL DEFAULT 0,
   inventoryDays double precision NOT NULL DEFAULT 0,
   financingRate double precision NOT NULL DEFAULT 0,
   managementFee double precision NOT NULL DEFAULT 0,
   monthlyRebate double precision NOT NULL DEFAULT 0,
   quarterlyRebate double precision NOT NULL DEFAULT 0,
   satisfactionRebate double precision NOT NULL DEFAULT 0,
   pickupRebate double precision NOT NULL DEFAULT 0,
   biddingSubsidy double precision NOT NULL DEFAULT 0,
   terminalSalesBonus double precision NOT NULL DEFAULT 0,
   otherRebate double precision NOT NULL DEFAULT 0,
   rebateAdjustment double precision NOT NULL DEFAULT 0,
   vehiclePushMoney double precision NOT NULL DEFAULT 0,
   accessoryPushMoney double precision NOT NULL DEFAULT 0,
   insurancePushMoney double precision NOT NULL DEFAULT 0,
   lpPushMoney double precision NOT NULL DEFAULT 0,
   installmentPushMoney double precision NOT NULL DEFAULT 0,
   extendedWarrantyPushMoney double precision NOT NULL DEFAULT 0,
   financialLeasingPushMoney double precision NOT NULL DEFAULT 0,
   memberCardPushMoney double precision NOT NULL DEFAULT 0,
   exchangePushMoney double precision NOT NULL DEFAULT 0,
   otherPushMoney double precision NOT NULL DEFAULT 0,
   pushMoneyDeduction double precision NOT NULL DEFAULT 0,
   version integer NOT NULL,
   updatedBy varchar(20) NOT NULL,
   CONSTRAINT DVSL_PK PRIMARY KEY (contractNo, timestamp)
) 
WITH (
  OIDS = FALSE
)
;
CREATE TABLE DealerPostSalesLedger
(
   timestamp timestamp without time zone NOT NULL,
   timeEnd timestamp without time zone NOT NULL,
   validDate date NOT NULL,
   workOrderNo integer NOT NULL,
   dealerID integer NOT NULL,
   purchaseDate date,
   mileage double precision NOT NULL DEFAULT 0,
   lpNumber varchar(100),
   customerName varchar(100),
   color varchar(100),
   frameNo varchar(100),
   model varchar(100),
   enterFactoryDate date,
   exitFactoryDate date,
   customerType varchar(100),
   insuranceAgency varchar(100),
   insuranceDueDate date,
   insuranceClaimNumber integer NOT NULL DEFAULT 0,
   maintenancePostSalesConsultant varchar(100),
   maintenanceTechnician varchar(100),
   maintenanceType varchar(100),
   insuranceType varchar(100),
   bodyShopPostSalesConsultant varchar(100),
   sheetMetalTechinician varchar(100),
   paintSprayTechinician varchar(100),
   mineralEngineOil boolean NOT NULL DEFAULT FALSE,
   synthesizedEngineOil boolean NOT NULL DEFAULT FALSE,
   airFilterElement boolean NOT NULL DEFAULT FALSE,
   airConditionerFilterElement boolean NOT NULL DEFAULT FALSE,
   gasolineFilterElement boolean NOT NULL DEFAULT FALSE,
   brakeFluid boolean NOT NULL DEFAULT FALSE,
   sparkPlug boolean NOT NULL DEFAULT FALSE,
   directionEngineOil boolean NOT NULL DEFAULT FALSE,
   transmissionOil boolean NOT NULL DEFAULT FALSE,
   coolingFluid boolean NOT NULL DEFAULT FALSE,
   timingChain boolean NOT NULL DEFAULT FALSE,
   lubricationSystemClean boolean NOT NULL DEFAULT FALSE,
   transmissionClean boolean NOT NULL DEFAULT FALSE,
   directionSystemClean boolean NOT NULL DEFAULT FALSE,
   coolingSystemClean boolean NOT NULL DEFAULT FALSE,
   airConditionerClean boolean NOT NULL DEFAULT FALSE,
   fuelSystemClean boolean NOT NULL DEFAULT FALSE,
   otherSystemClean boolean NOT NULL DEFAULT FALSE,
   maintenanceProductAmount integer NOT NULL DEFAULT 0,
   tyreCount integer NOT NULL DEFAULT 0,
   batteryCount integer NOT NULL DEFAULT 0,
   sparkPlugCount integer NOT NULL DEFAULT 0,
   wiperBladeCount integer NOT NULL DEFAULT 0,
   maintenanceManHourRevenuePaidPart double precision NOT NULL DEFAULT 0,
   maintenanceManHourDiscountPaidPart double precision NOT NULL DEFAULT 0,
   maintenanceManHourCouponPaidPart double precision NOT NULL DEFAULT 0,
   maintenanceManHourCostPaidPart double precision NOT NULL DEFAULT 0,
   maintenanceManHourRevenueUnpaidPart double precision NOT NULL DEFAULT 0,
   maintenanceManHourCostUnpaidPart double precision NOT NULL DEFAULT 0,
   sheetMetalManHourRevenue double precision NOT NULL DEFAULT 0,
   paintSprayManHourRevenue double precision NOT NULL DEFAULT 0,
   bodyShopManHourDiscount double precision NOT NULL DEFAULT 0,
   bodyShopManHourCoupon double precision NOT NULL DEFAULT 0,
   bodyShopManHourCost double precision NOT NULL DEFAULT 0,
   accessoryManHourRevenue double precision NOT NULL DEFAULT 0,
   accessoryManHourDiscount double precision NOT NULL DEFAULT 0,
   accessoryManHourCoupon double precision NOT NULL DEFAULT 0,
   accessoryManHourCost double precision NOT NULL DEFAULT 0,
   otherManHourRevenue double precision NOT NULL DEFAULT 0,
   otherManHourDiscount double precision NOT NULL DEFAULT 0,
   otherManHourCoupon double precision NOT NULL DEFAULT 0,
   otherManHourCost double precision NOT NULL DEFAULT 0,
   otherManHourMargin double precision NOT NULL DEFAULT 0,
   maintenancePartsRevenue double precision NOT NULL DEFAULT 0,
   maintenancePartsDiscount double precision NOT NULL DEFAULT 0,
   maintenancePartsCoupon double precision NOT NULL DEFAULT 0,
   maintenancePartsCost double precision NOT NULL DEFAULT 0,
   accessoryPartsRevenue double precision NOT NULL DEFAULT 0,
   accessoryPartsDiscount double precision NOT NULL DEFAULT 0,
   accessoryPartsCoupon double precision NOT NULL DEFAULT 0,
   accessoryPartsCost double precision NOT NULL DEFAULT 0,
   maintenanceProductRevenue double precision NOT NULL DEFAULT 0,
   maintenanceProductDiscount double precision NOT NULL DEFAULT 0,
   maintenanceProductCoupon double precision NOT NULL DEFAULT 0,
   maintenanceProductCost double precision NOT NULL DEFAULT 0,
   vehicleDecorationRevenue double precision NOT NULL DEFAULT 0,
   vehicleDecorationDiscount double precision NOT NULL DEFAULT 0,
   vehicleDecorationCoupon double precision NOT NULL DEFAULT 0,
   vehicleDecorationCost double precision NOT NULL DEFAULT 0,
   version integer NOT NULL,
   updatedBy varchar(20) NOT NULL,
   CONSTRAINT DPSL_PK PRIMARY KEY (workOrderNo, timestamp)
) 
WITH (
  OIDS = FALSE
)
;